plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.swifttech'
version = '0.0.1-SNAPSHOT'
description = 'sr-products-services-real'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    implementation files("D:\\IdeaProjects\\sr-products-services-real\\src\\main\\libs\\edx-data-management-0.1.19-plain.jar")


    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'


    //dm reqs
    //bucket
    implementation 'io.minio:minio:8.6.0'

    //Aws
    implementation 'software.amazon.awssdk:sesv2:2.40.8'
    implementation 'software.amazon.awssdk:s3:2.40.8'

    implementation 'org.apache.tika:tika-core:3.2.3'
    implementation 'org.modelmapper:modelmapper:3.2.0'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation "org.apache.commons:commons-csv:1.10.0"



}

tasks.named('test') {
    useJUnitPlatform()
}
