
# ========================================
# USER SUCCESS MESSAGES
# ========================================
USR-USR-CRE-100=User created successfully.
USR-USR-UPD-100=User updated successfully.
USR-USR-UST-100=User status updated successfully.
USR-USR-BYI-100=User retrieved successfully.
USR-USR-LST-100=User list fetched successfully.
USR-USR-PLS-100=User paginated list fetched successfully.
USR-USR-GIS-100=User paginated list fetched successfully.
USR-USR-UUG-100=User group updated successfully
USR-USR-CPW-100=Password changed successfully
USR-USR-FID-100=User retrieved successfully.
# ========================================
# ROLE SUCCESS MESSAGES
# ========================================
USR-ROL-CRE-100=Role created successfully.
USR-ROL-UPD-100=Role updated successfully.
USR-ROL-UST-100=Role status updated successfully.
USR-ROL-BYI-100=Role retrieved successfully.
USR-ROL-LST-100=Role list fetched successfully.
USR-ROL-PLS-100=Role paginated list fetched successfully.
# ========================================
# GROUP SUCCESS MESSAGES
# ========================================
USR-GRP-CRE-100=Group created successfully.
USR-GRP-UPD-100=Group updated successfully.
USR-GRP-UST-100=Group status updated successfully.
USR-GRP-BYI-100=Group retrieved successfully.
USR-GRP-LST-100=Group list fetched successfully.
USR-GRP-PLS-100=Group paginated list fetched successfully.
# ========================================
# POLICY SUCCESS MESSAGES
# ========================================
USR-POL-CRE-100=Policy created successfully.
USR-POL-UPD-100=Policy updated successfully.
USR-POL-UST-100=Policy status updated successfully.
USR-POL-BYI-100=Policy retrieved successfully.
USR-POL-LST-100=Policy list fetched successfully.
USR-POL-PLS-100=Policy paginated list fetched successfully.
# ========================================
# AUTHENTICATION SUCCESS MESSAGES
# ========================================
USR-AUT-GAC-100=Authentication challenge generated successfully.
USR-AUT-GLD-100=Login details fetched successfully.
USR-AUT-GTN-100=Token generated successfully.
USR-AUT-GCT-100=Customer token generated successfully.
USR-AUT-ART-100=Admin token refreshed successfully.
USR-AUT-ALG-100=Logout successfully.
USR-AUT-CRT-100=Customer token refreshed successfully.
USR-AUT-CLG-100=Logout successfully.
USR-AUT-CBL-100=Challenge-based login successful.
USR-AUT-RFP-100=A one-time password (OTP) has been sent to your registered email for verification.
USR-AUT-VYO-100=OTP validated successfully.
USR-AUT-CHP-100=Password changed successfully.
USR-AUT-BMS-100=Biometric setup completed successfully.
USR-AUT-CUE-100=User existence verified successfully.
USR-AUT-GPP-100=Password policy retrieved successfully.
USR-USR-UCP-100=Password changed successfully.

# ========================================
# Customer Messages
# ========================================
CUS-AUS-RUS-100=User Registered Successfully.
CUS-AUS-SKY-100= KYC skipped. Please complete your KYC soon to enjoy all features.
CUS-AUS-UEX-101 = User account validated Successfully.
CUS-AUS-USL-100= Selfie image uploaded successfully.
CUS-CSM-MSC-100= Mobile Screen Configuration saved Successfully.
CUS-CSM-USM-100 = Mobile Screen Configuration updated Successfully.
# ========================================
# OTP Messages
# ========================================
CUS-AUS-OTV-100 = OTP Validated Successfully.
# ========================================
# KYC Messages
# ========================================
CUS-AUS-KYC-100=Kyc Registered successfully.
# ========================================
# Beneficiary Messages
# ========================================
CUS-BFS-CRE-100=Beneficiary Created Successfully.
CUS-BFS-FBP-100=Beneficiary List Fetched Successfully.
# ========================================
# Document Messages
# ========================================
CUS-DOC-UPL-100=Document Uploaded Successfully. Please proceed .
CUS-DOC-RNW-100= Document Renewal initiated Successfully.


#############        Master           #################

################### PAYMENT INSTRUMENT ##############
MST-PMT-CRE-100 = Payment instrument created successfully.
MST-PMT-UPD-100 =Payment instrument updated successfully.
MST-PMT-BYI-100= Payment instrument details.
MST-PMT-LST-100 = Payment instrument paginated list fetched successfully.
MST-PMT-PLS-100 = Payment instrument list fetched successfully.


################### INSTRUMENT TYPE ##############
MST-INT-CRE-100 = Instrument type created successfully.
MST-INT-UPD-100 =Instrument type updated successfully.
MST-INT-BYI-100= Instrument type details.
MST-INT-LST-100 = Instrument type list fetched successfully.
MST-INT-PLS-100 = Instrument type paginated list fetched successfully.

MST-USR-LST-100= User type list fetched successfully.

###################Promotion Type##################
MST-PRT-CRE-100 = Promotion type created successfully.
MST-PRT-UPD-100 = Promotion type updated successfully.
MST-PRT-PLS-100 = Promotion type paginated list fetched successfully.
MST-PRT-LST-100 = Promotion type list fetched successfully.
MST-PRT-BYI-100 = Promotion type details.
MST-PRT-UST-100 = Status changed successfully.


###################Promotion Channel##################
MST-PMC-CRE-100 = Promotion channel created successfully.
MST-PMC-UPD-100 = Promotion channel updated successfully.
MST-PMC-PLS-100 = Promotion channel paginated list fetched successfully.
MST-PMC-LST-100 = Promotion channel list fetched successfully.
MST-PMC-UST-100 = Status changed successfully.
MST-PMC-BYI-100 = Promotion channel details.


##############Service Category################
MST-SRC-CRE-100 = Service created successfully.
MST-SRC-LST-100 = Service List fetched successfully.



#############Promotion##################
MST-PRO-CRE-100= Promotion created successfully.
MST-PRO-UPD-100= Promotion updated successfully.
MST-PRO-BYI-100= Promotion details.
MST-PRO-PLS-100= Promotion paginated list fetched successfully.
MST-PRO-LST-100= Promotion list fetched successfully.
MST-PRO-UST-100= Status changed successfully.



#################COUNTRY#############.
MST-CON-CRE-100= Country created successfully.
MST-CON-UPD-100= Country updated successfully.
MST-CON-BYI-100= Country details
MST-CON-LST-100= Country list fetched successfully.
MST-CON-PLS-100= Country paginated list fetched successfully.
MST-CON-UST-100= Status changed successfully.

############# User Type ####################
MST-UST-CRE-100= User type created successfully.
MST-UST-LST-100= User type list fetched successfully.


#################Time Zone#############.
MST-TMZ-CRE-100= Time zone created successfully.
MST-TMZ-UPD-100= Time zone updated successfully.
MST-TMZ-BYI-100= Time zone details
MST-TMZ-LST-100= Time zone list fetched successfully.
MST-TMZ-PLS-100= Time zone paginated list fetched successfully.
MST-TMZ-UST-100= Status changed successfully.

##################Time Format##################
MST-TFT-CRE-100= Time format created successfully.
MST-TFT-UPD-100= Time format updated successfully.
MST-TFT-BYI-100= Time format details.
MST-TFT-LST-100= Time format list fetched successfully.
MST-TFT-PLS-100= Time format paginated list fetched successfully.
MST-TFT-UST-100= Status changed successfully.

##################Orientation##################
MST-ORI-CRE-100= Orientation created successfully.
MST-ORI-UPD-100= Orientation updated successfully.
MST-ORI-BYI-100= Orientation details.
MST-ORI-LST-100= Orientation list fetched successfully.
MST-ORI-PLS-100= Orientation paginated list fetched successfully.
MST-ORI-UST-100= Status changed successfully.

##################Number Format##################
MST-NFT-CRE-100= Number format created successfully.
MST-NFT-UPD-100= Number format updated successfully.
MST-NFT-BYI-100= Number format details.
MST-NFT-LST-100= Number format list fetched successfully.
MST-NFT-PLS-100= Number format paginated list fetched successfully.
MST-NFT-UST-100= Status changed successfully.

##################System Version##################
MST-SYV-CRE-100= System version created successfully.
MST-SYV-UPD-100= System version updated successfully.
MST-SYV-BYI-100= System version details.
MST-SYV-LST-100= System version list fetched successfully.
MST-SYV-PLS-100= System version paginated list fetched successfully.
MST-SYV-UST-100= Status changed successfully.
MST-SYV-LSV-100= System version latest version.



##################Date Format##################
MST-DFT-CRE-100= Date format created successfully.
MST-DFT-UPD-100= Date format updated successfully.
MST-DFT-BYI-100= Date format details.
MST-DFT-LST-100= Date format list fetched successfully.
MST-DFT-PLS-100= Date format paginated list fetched successfully.
MST-DFT-UST-100= Status changed successfully.

##################  Language  ##################
MST-LAN-CRE-100= Language created successfully.
MST-LAN-UPD-100= Language updated successfully.
MST-LAN-BYI-100= Language details.
MST-LAN-LST-100= Language list fetched successfully.
MST-LAN-PLS-100= Language paginated list fetched successfully.
MST-LAN-UST-100= Status changed successfully.


##################Exchange Rate##################
TXN-ERC-CEX-100=Default exchange rate calculation success.
TXN-ERC-CRA-100=Exchange rate calculate success.
TXN-ERC-PPM-100=Payment mode data fetch success.

##################Transaction##################
TXN-TRA-SET-100=Transaction created successfully.
TXN-TRA-GTH-100=Transaction history fetch successfully.
TXN-TRA-GPS-100=Payment service type fetch successfully.
TXN-TRA-UPT-100=Transaction status update successfully.

TXN-TXN-CDD-100=Due Diligence Data Fetched Successfully.






####################     RSP     #######################

###########################.....RSP.....###########################
RSP-RSP-CRE-100 = The RSP has been created successfully.
RSP-RSP-BYI-100 = Rsp details.
RSP-RSP-LST-100= Rsp list fetched successfully.
RSP-RSP-PLS-100= Rsp paginated list fetched successfully.
RSP-RSP-VRS-100= Rsp validated successfully.

RSP-RSP-RRP-100= Resolved rsp.

RSP-LRS-GLR-100= Legal File fetched successfully.
RSP-LRS-ULR-100= Legal File uploaded successfully.



########################.....AuthenticationProperties.......#################
RSP-AUP-CRE-100= Authentication properties created successfully.
RSP-AUP-LST-100= Authentication properties list fetched successfully.
RSP-AUP-UPD-100= Authentication properties updated successfully.
RSP-AUP-BYI-100= Authentication properties details.
RSP-AUP-PLS-100= Authentication properties paginated list fetched successfully.
RSP-AUP-UST-100= Status changed successfully.



########################.....SupportedCorridors.......#################
RSP-SCD-CRE-100= Supported corridors created successfully.
RSP-SCD-LST-100= List of supported corridors(source country).
RSP-SCD-LST-101= List of destination countries of source cuntries.


##################Payment Service Type#############
RSP-PST-CRE-100= payment service type created successfully.
RSP-PST-PLS-100= Payment service type list fetched successfully.
RSP-PST-UPD-100 = Payment service type updated successfully.



# ========================================
# Admin SUCCESS MESSAGES
# ========================================

ADM-IND-CRE-100 = User created successfully.
ADM-IND-UPD-100 = User updated successfully.
ADM-IND-UST-100 = User status updated successfully.
ADM-IND-GET-100 = User retrieved successfully.
ADM-IND-LST-100 = User list fetched successfully.
ADM-IND-LUR-100 = User retrieved successfully.



ADM-SAL-LST-100 = Salutation list fetched successfully.
USR-USR-BLS-100= Biometric setup successfully







